CREATE PROCEDURE GetFlightDetailsPNR
	@PNR char(6),
	@Surname varchar(50)
AS
BEGIN
	SELECT BOOKING.BookingPNR, PASSENGER.Fname, PASSENGER.Lname, PASSENGER.PassportNo, 
			FLIGHT.Airline, FLIGHT.FlightNo, FLIGHT.Time, FLIGHT.PlaneType, 
			FLIGHT.City, FLIGHT.Terminal, FLIGHT.ArrDep, FLIGHTINSTANCE.Date, PLANETYPE.Manufacturer
	FROM BOOKING, PASSENGER, BOOKINGPASSENGER, FLIGHT, FLIGHTINSTANCE, PLANETYPE
	WHERE BOOKINGPASSENGER.BookingPNR = BOOKING.BookingPNR 
			AND BOOKINGPASSENGER.PassportNo = PASSENGER.PassportNo 
			AND BOOKING.FlightInstance = FLIGHTINSTANCE.InstanceNo 
			AND FLIGHTINSTANCE.FlightNo = FLIGHT.FlightNo 
			AND PLANETYPE.Name = FLIGHT.PlaneType 
			AND BOOKING.BookingPNR = @PNR
			AND PASSENGER.Lname = @Surname
END
GO
