CREATE PROCEDURE SelectPassengerByAirline
	@Airline varchar(50)
AS
BEGIN
	SELECT PASSENGER.Fname, PASSENGER.Lname, PASSENGER.Nationality, PASSENGER.PassportNo, PASSENGER.Status
	FROM PASSENGER, BOOKINGPASSENGER, BOOKING, FLIGHTINSTANCE, FLIGHT
	WHERE PASSENGER.PassportNo = BOOKINGPASSENGER.PassportNo AND BOOKINGPASSENGER.BookingPNR = BOOKING.BookingPNR AND BOOKING.FlightInstance = FLIGHTINSTANCE.InstanceNo AND FLIGHTINSTANCE.FlightNo = FLIGHT.FlightNo AND FLIGHT.Airline = @Airline
END
GO
